name: Run License Plate Model

on:
  workflow_dispatch:

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install ultralytics pillow pytesseract numpy opencv-python-headless flask

      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-eng libtesseract-dev libleptonica-dev
          echo "✅ Tesseract Installed!"

      - name: Check Tesseract Path
        run: which tesseract

      - name: Verify Tesseract installation
        run: tesseract --version

      - name: Verify model file
        run: |
          if [ ! -f "yolov8_license_plate.pt" ]; then
            echo "❌ النموذج غير موجود! تأكد من رفعه إلى GitHub."
            exit 1
          fi
          echo "✅ النموذج موجود وجاهز!"

      - name: Run prediction script
        run: python app.py

      - name: Verify result.json file
        run: |
          if [ ! -f "result.json" ]; then
            echo "❌ ملف `result.json` غير موجود! تحقق من `app.py`."
            exit 1
          fi
          echo "✅ ملف `result.json` موجود!"

      - name: Upload prediction result
        uses: actions/upload-artifact@v4
        with:
          name: prediction-result
          path: result.json
